spring.application.name=firstSpringBatch
spring.batch.job.enabled=false
server.port=8081


spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.password=root
spring.datasource.username=postgres

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-postgres.sql
